# Example Configuration for Proxy Speed Monitor
# Rename this file to config.yaml and fill in your details.

proxy:
  # (Required) The hostname or IP address of your proxy server.
  host: 192.168.1.100
  # (Required) The port number of your proxy server.
  port: 8080

monitoring:
  # (Required) A list of websites to use for monitoring.
  websites:
    - https://www.google.com
    - https://www.github.com
  # (Required) The path to the Excel file where logs will be stored.
  log_file: /var/log/proxy_monitor.xlsx

# (Optional) Settings for email notifications.
email_alerts:
  recipient_email: your_email@example.com

  # Use the local MTA on your *nix system, by default SMTP on port 25 is used
  use_local_mta: true
  # (Optional) Use the specified sendmail executable for local submission
  # sendmail_path: /usr/sbin/sendmail

  # These settings are only needed if use_local_mta is false.
  smtp_server: smtp.example.com
  smtp_port: 587
  smtp_user: your_email@example.com
  smtp_password: your_password